<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click image in google</name>
   <tag></tag>
   <elementGuidId>a04c3395-22c1-4aab-b185-28fea5c21db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//_top[@class = 'gb_g' and @data-pid = '2']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gbw']/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_g</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>_top</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
</WebElementEntity>
